package com.track.project.action;
/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 
package com.dts.project.action;

import java.io.IOException;

import javax.jms.Session;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;


import com.dts.core.util.CoreHash;
import com.dts.project.dao.QueryDAO;



public class ViewQuerys extends HttpServlet{
	
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		doPost(req,resp);
	}
	@Override
	public void doPost(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		
		try{
			HttpSession session=req.getSession();
			String user = (String)session.getAttribute("user");
			 QueryDAO querydao = new QueryDAO();
             CoreHash aCoreHash = querydao.getQueryStatus(user);
             int size=aCoreHash.size();
             if(size!=0)
             {
            	 req.setAttribute("viewQueriesStatus",aCoreHash);
            	 return mapping.findForward("viewQueriesStatus");
             }
	}catch (Exception e) {
		
	}
	 ("norecords");
}
}*/